stages:
- test310
- test39
- test38
- test37
- coverage
- test

cache:
  paths:
  - ".coverage-py37"
  - ".coverage-py38"
  - ".coverage-py39"
  - ".coverage-py310"

before_script:
- ls -la
- apk add --no-cache --virtual .build-deps gcc linux-headers libc-dev libffi-dev openssl-dev
  git rust cargo
- python -m pip install -U pip
- pip install -r requirements.txt

test-37:
  stage: test37
  image: python:3.7-alpine
  dependencies:
  - test-38
  script:
  - pip install -r requirements-tests.txt
  - pycodestyle ./SOLIDserverRest/*.py ./SOLIDserverRest/adv/*.py
  - pytest -x --cov=./SOLIDserverRest --cov-config=tests/gitlab-coverage.rc tests/test*py
  - cp .coverage .coverage-py37
  only:
  - master
  - dev

test-38:
  stage: test38
  image: python:3.8-alpine
  dependencies:
  - test-39
  script:
  - pip install -r requirements-tests.txt
  - pycodestyle ./SOLIDserverRest/*.py ./SOLIDserverRest/adv/*.py
  - pytest -x --cov=./SOLIDserverRest --cov-config=tests/gitlab-coverage.rc tests/test*py
  - cp .coverage .coverage-py38
  only:
  - master
  - dev

test-39:
  stage: test39
  image: python:3.9-alpine
  dependencies:
  - test-310
  script:
  - pip install -r requirements-tests.txt
  - pycodestyle ./SOLIDserverRest/*.py ./SOLIDserverRest/adv/*.py
  - pytest -x --cov=./SOLIDserverRest --cov-config=tests/gitlab-coverage.rc tests/test*py
  - cp .coverage .coverage-py39
  only:
  - master
  - dev
  - "/^adv-.*/"
  - "/^fix.*/"
  - "/^\\d+-.*/"

test-310:
  stage: test310
  image: python:3.10-alpine
  script:
  - pip install -r requirements-tests.txt
  - pycodestyle ./SOLIDserverRest/*.py ./SOLIDserverRest/adv/*.py
  - pytest -x --cov=./SOLIDserverRest --cov-config=tests/gitlab-coverage.rc tests/test*py
  - cp .coverage .coverage-py310
  only:
  - master
  - dev
  - "/^adv-.*/"
  - "/^fix.*/"
  - "/^\\d+-.*/"

coverage:
  stage: coverage
  image: python:3.9-alpine
  dependencies:
  - test-310
  - test-39
  - test-38
  - test-37
  script:
  - pip install -r requirements-tests.txt
  - coverage combine .coverage-py310 .coverage-py37 .coverage-py38 .coverage-py39
  - coverage report -m
  - codecov
  only:
  - master
  - dev

sast:
  variables:
    SAST_EXCLUDED_PATHS: tests, examples, cli, docs
  stage: test

include:
- template: Security/SAST.gitlab-ci.yml
