stages:
   - test36
   - test37
   - test38
   - coverage

cache:
   paths:
      - .coverage-py36
      - .coverage-py37
      - .coverage-py38

before_script:
   - ls -la
   - apk add --no-cache --virtual .build-deps gcc linux-headers libc-dev libffi-dev openssl-dev git rust cargo
   - python -m pip install -U pip
   - pip install -r requirements.txt

test-36:
  stage: test36
  image: python:3.6-alpine
  script:
     - pip install -r requirements-tests.txt
     - pycodestyle ./SOLIDserverRest/*.py ./SOLIDserverRest/adv/*.py
     - pytest -x --cov=./SOLIDserverRest --cov-config=tests/gitlab-coverage.rc tests/test*py
     - cp .coverage .coverage-py36
  only:
     - master
     - dev
     - advanced-lib
     - /^fix.*/
     - /^\d+-.*/

test-37:
  stage: test37
  image: python:3.7-alpine
  dependencies:
    - test-36
  script:
     - pip install -r requirements-tests.txt
     - pycodestyle ./SOLIDserverRest/*.py ./SOLIDserverRest/adv/*.py
     - pytest -x --cov=./SOLIDserverRest --cov-config=tests/gitlab-coverage.rc tests/test*py
     - cp .coverage .coverage-py37
  only:
     - master
     - dev
     - advanced-lib
     - /^fix.*/

test-38:
  stage: test38
  image: python:3.8-alpine
  dependencies:
    - test-37
  script:
     - pip install -r requirements-tests.txt
     - pycodestyle ./SOLIDserverRest/*.py ./SOLIDserverRest/adv/*.py
     - pytest -x --cov=./SOLIDserverRest --cov-config=tests/gitlab-coverage.rc tests/test*py
     - cp .coverage .coverage-py38
  only:
     - master
     - dev
     - advanced-lib
     - /^fix.*/

coverage:
  stage: coverage
  image: python:3.8-alpine
  dependencies:
    - test-38
    - test-37
    - test-36
  script:
     - pip install -r requirements-tests.txt
     - coverage combine .coverage-py36 .coverage-py37 .coverage-py38
     - coverage report -m
     - codecov
  only:
     - master
     - dev
     - advanced-lib
     - /^fix.*/
